-PRA DERROTAR O OGRO, SEU ELEMENTO TEM
 Q SER O OPOSTO DO ELEMENTO DA ARMADURA DO INIMIGO

	MAGO_FOGO - OGRO_AGUA OU OGRO_FOGO - MAGO_AGUA
	MAGO_RAIO - OGRO_TERRA OU OGRO_RAIO - MAGO_TERRA

-VOCE TERA QUE CORRIGIR OS CODIGOS QUE APARECERAO PARA,
A PARTIR DE UMA LOGICA CORRETA, DERROTAR O INIMIGO

-OS CODIGOS PODERAO APRESENTAR ERROS DE LOGICA, 
SINTAXE E/OU SEMANTICA.

-CORRIJA O ERRO DA LINHA E APERTE ENTER
